FROM python:3.14-slim

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    git \
    git-lfs \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgl1 \
    wget && \
    git lfs install && \
    rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

EXPOSE 1376

CMD ["python", "app.py"]